/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'jewellery' : IDL.Null,
  'nails' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        ProductCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, ShippingAddress, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'seedProducts' : IDL.Func([], [], []),
  'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'jewellery' : IDL.Null,
    'nails' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          ProductCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, ShippingAddress, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedProducts' : IDL.Func([], [], []),
    'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };